# docker-compose.yml
services:
  fragments:
    init: true
    build: .
    environment:
      - API_URL=http://localhost:8080
      - HTPASSWD_FILE=/app/tests/.htpasswd
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - AUTH_TYPE=basic
      - AWS_COGNITO_POOL_ID=
      - AWS_COGNITO_CLIENT_ID=
      - AWS_REGION=us-east-1
      - AWS_S3_ENDPOINT_URL=http://localstack:4566
      - AWS_DYNAMODB_ENDPOINT_URL=http://dynamodb-local:8000
      - AWS_S3_BUCKET_NAME=fragments
      - AWS_DYNAMODB_TABLE_NAME=fragments
      - AWS_ACCESS_KEY_ID=test
      - AWS_SECRET_ACCESS_KEY=test
      - AWS_SESSION_TOKEN=test

    ports:
      - '8080:8080'
    volumes:
      - ./tests:/app/tests
    depends_on:
      - dynamodb-local
      - localstack

  dynamodb-local:
    image: amazon/dynamodb-local
    ports:
      - '8000:8000'
    command: ['-jar', 'DynamoDBLocal.jar', '-inMemory']

  localstack:
    image: localstack/localstack
    ports:
      - '4566:4566'
    environment:
      - SERVICES=s3
      - DEFAULT_REGION=us-east-1
